(use-package copilot
  :defer t
  :straight (:host github :repo "zerolfx/copilot.el" :files ("dist" "*.el"))
  :hook (prog-mode . copilot-mode)
  :bind (:map copilot-completion-map
              ("C-j" . copilot-accept-completion)
              ("M-j" . copilot-clear-overlay)
              ("C-c j n" . copilot-next-completion)
              ("C-c j p" . copilot-previous-completion))
  :init
  (setq copilot--indent-warning-printed-p t)
  )

(use-package gptel
  :config
  (setq gptel-modle '("gpt-4-1106-preview"))
  (defvar gptel-quick--history nil)

  (defvar gptel-commit-summary-prompt "You will be provided with text generated by \"git diff\" delimited by triple backticks. Your task is to summarize the change and write a commit message.
​The commit message should be structured as follows:
​
<type>[optional scope]: <description>
​
```
%s
```")
  ​
  (defun gptel-commit-summary ()
    "Summarize current git commit."
    (interactive)
    (let ((gptel--system-message "You are an expert programmer, and you are trying to summarize a code change.")
          (user-prompt (format
                        gptel-commit-summary-prompt
                        (shell-command-to-string "git diff --cached"))))
      (gptel-request user-prompt
                     :stream t
                     :in-place t)))
  
  (defun gptel-quick (prompt)
    (interactive (list (read-string "Ask ChatGPT: " nil gptel-quick--history)))
    (when (string= prompt "") (user-error "A prompt is required."))
    (gptel-request
     prompt
     :callback
     (lambda (response info)
       (if (not response)
           (message "gptel-quick failed with message: %s" (plist-get info :status))
         (with-current-buffer (get-buffer-create "*gptel-quick*")
           (let ((inhibit-read-only t))
             (erase-buffer)
             (insert response))
           (special-mode)
           (display-buffer (current-buffer)
                           `((display-buffer-in-side-window)
                             (side . bottom)
                             (window-height . ,#'fit-window-to-buffer))))))))

  (defun gptel-rewrite-and-replace (bounds &optional directive)
    (interactive
     (list
      (cond
       ((use-region-p) (cons (region-beginning) (region-end)))
       ((derived-mode-p 'text-mode)
        (list (bounds-of-thing-at-point 'sentence)))
       (t (cons (line-beginning-position) (line-end-position))))
      (and current-prefix-arg
           (read-string "ChatGPT Directive: "
                        "You are a prose editor. Rewrite my prompt more professionally."))))
    (gptel-request
     (buffer-substring-no-properties (car bounds) (cdr bounds)) ;the prompt
     :system (or directive "You are a prose editor. Rewrite my prompt more professionally.")
     :buffer (current-buffer)
     :context (cons (set-marker (make-marker) (car bounds))
                    (set-marker (make-marker) (cdr bounds)))
     :callback
     (lambda (response info)
       (if (not response)
           (message "ChatGPT response failed with: %s" (plist-get info :status))
         (let* ((bounds (plist-get info :context))
                (beg (car bounds))
                (end (cdr bounds))
                (buf (plist-get info :buffer)))
           (with-current-buffer buf
             (save-excursion
               (goto-char beg)
               (kill-region beg end)
               (insert response)
               (set-marker beg nil)
               (set-marker end nil)
               (message "Rewrote line. Original line saved to kill-ring."))))))))
  :bind (
         ("C-c I" . gptel-quick)
         ("C-c i s" . gptel-send)
         ("C-c i r" . gptel-rewrite-and-replace)
         ("C-c i b" . gptel))
  )

(provide 'init-copilot)
